export type InspirationSloganLocale = 'zh-CN' | 'en';
export type InspirationSlogan = Readonly<Record<InspirationSloganLocale, string>>;

// Keep translations together so language changes preserve the current idea.
export const inspirationSlogans: readonly InspirationSlogan[] = [
  {"zh-CN": "从一个念头，到一个世界。", "en": "From one idea to a whole new world."},
  {"zh-CN": "让小想法，长成大未来。", "en": "Small ideas grow into big futures."},
  {"zh-CN": "让每个小目标，都通向更大的梦想。", "en": "Every small step leads to something bigger."},
  {"zh-CN": "把小目标，做成大事情。", "en": "Turn small goals into big things."},
  {"zh-CN": "从微小开始，向无限生长。", "en": "Start small. Grow beyond limits."},
  {"zh-CN": "让想法，不止停在想法。", "en": "Ideas are meant to go further."},
  {"zh-CN": "起于微小，成于无限。", "en": "Start small. Become limitless."},
  {"zh-CN": "把一点可能，变成无限可能。", "en": "Turn one possibility into endless possibilities."},
  {"zh-CN": "从小事开始，把梦想做大。", "en": "Start small. Dream bigger."},
  {"zh-CN": "每一个大梦想，都从一个小念头开始。", "en": "Every big dream starts with a small idea."},
  {"zh-CN": "从想到，到做到，再到更远。", "en": "Think it. Make it. Take it further."},
  {"zh-CN": "让每一个开始，都值得更大的结果。", "en": "Let every beginning lead to something greater."},
  {"zh-CN": "让灵感，走得更远。", "en": "Take inspiration further."},
  {"zh-CN": "从一点灵感，到无限可能。", "en": "From a spark to endless possibilities."},
  {"zh-CN": "让每一次灵感，都有结果。", "en": "Turn every spark into something real."},
  {"zh-CN": "灵感很小，未来很大。", "en": "A small spark. A bigger future."},
  {"zh-CN": "让灵感生长，让梦想发生。", "en": "Let ideas grow. Let dreams take shape."},
  {"zh-CN": "从一闪而过，到真正实现。", "en": "From a passing spark to something real."},
  {"zh-CN": "让灵感被看见。", "en": "Bring your ideas to life."},
  {"zh-CN": "灵感只是开始。", "en": "Inspiration is just the beginning."},
  {"zh-CN": "每个大梦想，都始于一点灵感。", "en": "Every big dream begins with a spark."},
  {"zh-CN": "让灵感，不止停在脑海里。", "en": "Take ideas beyond your imagination."},
  {"zh-CN": "从灵光一现，到梦想成真。", "en": "From a spark to something real."},
  {"zh-CN": "给灵感一个开始，给梦想一个结果。", "en": "Give ideas a start. Give dreams a future."},
  {"zh-CN": "把一瞬间的灵感，变成长久的可能。", "en": "Turn a moment of inspiration into lasting possibilities."},
  {"zh-CN": "从一个念头，生长出无限未来。", "en": "One idea can grow into endless possibilities."},
  {"zh-CN": "让灵感成为现实的起点。", "en": "Let inspiration be where reality begins."},
  {"zh-CN": "让一粒念头，长成一片远方。", "en": "Let a single idea grow into somewhere new."},
  {"zh-CN": "从一束微光，走向万千星河。", "en": "From a single spark to a sky full of stars."},
  {"zh-CN": "让最初的灵感，抵达最远的地方。", "en": "Let your first spark take you further than you imagined."},
  {"zh-CN": "一个念头落下，未来便开始生长。", "en": "Plant an idea, and a future begins to grow."},
  {"zh-CN": "从心里的一点微光，到眼前的一整个世界。", "en": "From a spark within to a world before you."},
  {"zh-CN": "让微小的开始，慢慢长成辽阔。", "en": "Let small beginnings grow into something vast."},
  {"zh-CN": "所有远方，都曾只是心里的一点念想。", "en": "Every faraway place begins as a thought."},
  {"zh-CN": "让一闪而过的灵感，有机会成为永恒。", "en": "Give a fleeting spark the chance to become something lasting."},
  {"zh-CN": "从一个念头出发，把远方一步步写成现实。", "en": "Start with an idea. Build your way toward the horizon."},
  {"zh-CN": "愿每一颗小小的念头，都有长大的机会。", "en": "Give every little idea room to grow."},
  {"zh-CN": "一念初生，万物渐明。", "en": "One spark, and everything begins to unfold."},
  {"zh-CN": "让灵感生根，让梦想开花。", "en": "Let ideas take root and dreams come alive."},
  {"zh-CN": "从微光开始，直到照亮自己的远方。", "en": "Begin with a spark. Light the way ahead."},
  {"zh-CN": "最初只是一念，后来成了整个世界。", "en": "It started as an idea. It became a world."},
  {"zh-CN": "让藏在心里的那一点光，慢慢有了形状。", "en": "Give shape to the spark within."},
  {"zh-CN": "从一瞬心动，到一生想抵达的地方。", "en": "From a moment of inspiration to somewhere worth reaching."},
  {"zh-CN": "每一次灵光闪现，都藏着一个尚未发生的世界。", "en": "Every spark holds a world waiting to happen."},
  {"zh-CN": "把心中的一点微澜，慢慢推向辽阔。", "en": "Let a small ripple grow into something boundless."},
  {"zh-CN": "让今天的一点想象，成为明天真实的风景。", "en": "Turn today’s imagination into tomorrow’s reality."},
  {"zh-CN": "始于微小，向无限生长。", "en": "Start small. Grow beyond limits."},
  {"zh-CN": "从一点灵感，到更大的可能。", "en": "From a spark to something bigger."},
  {"zh-CN": "从想到、做到，再到更远。", "en": "Think it. Make it. Take it further."},
  {"zh-CN": "一点灵感，一个更大的未来。", "en": "A small spark. A bigger future."},
  {"zh-CN": "一切，从一个念头开始。", "en": "It starts with an idea."},
  {"zh-CN": "想法，本就应该走得更远。", "en": "Ideas are meant to go further."},
  {"zh-CN": "让每一个想法都有生长的空间。", "en": "Give every idea room to grow."},
  {"zh-CN": "从一点灵感，到一个充满可能的世界。", "en": "From a spark to a world of possibilities."},
  {"zh-CN": "每一点灵感里，都藏着一个尚未发生的世界。", "en": "Every spark holds a world waiting to happen."},
  {"zh-CN": "最初只是一个念头，后来成了一个世界。", "en": "It started as an idea. It became a world."},
];
